- name: Install required PostgreSQL Python library
  apt:
    name: python3-psycopg2
    state: present

- name: Create sonar PostgreSQL user (shell fallback)
  become: true
  shell: |
    sudo -u postgres psql -c "CREATE USER {{ postgres_user }} WITH PASSWORD '{{ postgres_password }}';" || \
    sudo -u postgres psql -c "ALTER USER {{ postgres_user }} WITH PASSWORD '{{ postgres_password }}';"
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Create sonar PostgreSQL database (shell fallback)
  become: true
  shell: |
    sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = '{{ postgres_db }}'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE DATABASE {{ postgres_db }} OWNER {{ postgres_user }};"
  args:
    executable: /bin/bash

