- name: Ensure SonarQube group exists
  group:
    name: "{{ sonarqube_group }}"
    state: present

- name: Ensure SonarQube user exists
  user:
    name: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"
    home: "{{ sonarqube_dir }}"
    create_home: no
    shell: /bin/bash
    state: present

- name: Download SonarQube
  get_url:
    url: "{{ sonarqube_zip_url }}"
    dest: "/tmp/sonarqube.zip"

- name: Extract SonarQube
  unarchive:
    src: /tmp/sonarqube.zip
    dest: /opt/
    remote_src: yes
    creates: "/opt/sonarqube-{{ sonarqube_version }}"

- name: Move SonarQube to target dir
  command: mv /opt/sonarqube-{{ sonarqube_version }} {{ sonarqube_dir }}
  args:
    creates: "{{ sonarqube_dir }}"

- name: Set permissions for SonarQube
  file:
    path: "{{ sonarqube_dir }}"
    owner: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"
    recurse: yes

- name: Update sonar.properties for DB settings
  lineinfile:
    path: "{{ sonarqube_dir }}/conf/sonar.properties"
    regexp: '^#?{{ item.key }}='
    line: "{{ item.key }}={{ item.value }}"
    state: present
  loop:
    - { key: "sonar.jdbc.username", value: "{{ postgres_user }}" }
    - { key: "sonar.jdbc.password", value: "{{ postgres_password }}" }
    - { key: "sonar.jdbc.url", value: "jdbc:postgresql://localhost:5432/{{ postgres_db }}" }
    - { key: "sonar.web.host", value: "0.0.0.0" }

